# Reusable validation jobs for both CD and PR workflows
name: Validation Jobs

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '22.4.1'
        type: string

jobs:
  unit-tests:
    name: '🛟 Run unit tests'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/node-yarn:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache yarn files
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            .yarn/install-state.gz
            node_modules
          key: node-modules-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Install Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run Unit Tests
        run: yarn test

  types:
    name: '🪪 Check typings'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/node-yarn:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache yarn files
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            .yarn/install-state.gz
            node_modules
          key: node-modules-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Install Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run Types Check
        run: yarn types

  lint:
    name: '🧹 Run lint'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/node-yarn:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache yarn files
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            .yarn/install-state.gz
            node_modules
          key: node-modules-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Install Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run Lint
        run: yarn lint

  lint-css:
    name: '🎨 Lint CSS'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/node-yarn:latest
    strategy:
      matrix:
        type: ['css', 'css-jsx']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache yarn files
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            .yarn/install-state.gz
            node_modules
          key: node-modules-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Install Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run Lint
        run: yarn lint:${{matrix.type}} 