compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": ^7.0.0-0
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": ^7.0.0-0
  rollup-plugin-auto-external@*:
    dependencies:
      rollup: ">=0.45.2"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
