nodeLinker: node-modules

packageExtensions:
  '@babel/plugin-transform-react-jsx@*':
    dependencies:
      '@babel/core': ^7.18.9
  '@babel/preset-env@*':
    dependencies:
      "@babel/core": ^7.0.0-0
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": ^7.0.0-0
  "@figspec/react@*":
    dependencies:
      react: ^16.14.0
  '@storybook/addon-styling-webpack@*':
    dependencies:
      webpack: ^5.0.0
  '@storybook/addon-docs@*':
    dependencies:
      "@babel/core": ^7.18.9
      webpack: ^5.75.0
  '@storybook/core-common@*':
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  '@storybook/docs-tools@*':
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  '@storybook/react@*':
    dependencies:
      require-from-string: ^2.0.2
  ts-node@*:
    dependencies:
      '@types/node': '*'
  rollup-plugin-auto-external@*:
    dependencies:
      rollup: '>=0.45.2'

yarnPath: .yarn/releases/yarn-3.6.4.cjs
